/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lec6_testing;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    
    /** 测试 get smallest 函数 */
    @Test
    public void test_get_smallest() {

        String[] test_array = new String[]{"a", "c" ,"b"};
        assertEquals(App.find_small(test_array), "a");
    }
}
