/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

tasks.withType<Jar> {
    /*
    DuplicatesStrategy.FAIL  ：如果存在重复项，构建过程将失败。
    DuplicatesStrategy.WARN   ：如果存在重复项，构建过程会继续，但会发出警告。
    DuplicatesStrategy.INCLUDE  ：包含所有重复项，不进行排除。
    DuplicatesStrategy.EXCLUDE  ： 排除所有重复项。
     */
    
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE // 或者使用其他策略
}
tasks.withType<Zip> {
    
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE // 或者使用其他策略
}

tasks.withType<Tar> {
    
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE // 或者使用其他策略
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // cs61b 的 library
    implementation(fileTree("../library-fa23") {
        include("*.jar")
        // exclude("failureaccess-1.0.1.jar",
        // "listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar"
        // )
        }
    )
    
}


application {
    // Define the main class for the application.
    mainClass.set("lectureCode_fa23")
}

// 下面这个不是必须的
sourceSets {
    named("main") {
        java {
            setSrcDirs(files("src/main/java")) // 设置为实际的源代码目录
        }
    }
}
